server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_project_db
    username: dev_user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
